(require 'cl)
(require 'ert)
(require 'ne2wm-utils)

(ert-deftest ne2wm:find-next-in-seq ()
  (let ((seq '(0 1 2 3 4)))
    (should (equal (ne2wm:find-next-in-seq seq 1) 2))
    (should (equal (ne2wm:find-next-in-seq seq 4) 0))
    (should (equal (ne2wm:find-next-in-seq seq 1 1) 2))
    (should (equal (ne2wm:find-next-in-seq seq 4 1) 0))
    (should (equal (ne2wm:find-next-in-seq seq 1 0) 1))
    (should (equal (ne2wm:find-next-in-seq seq 4 0) 4))
    (should (equal (ne2wm:find-next-in-seq seq 1 2) 3))
    (should (equal (ne2wm:find-next-in-seq seq 4 2) 1))
    (should (equal (ne2wm:find-next-in-seq seq 3 2) 0))
    (should (equal (ne2wm:find-next-in-seq seq 1 -1) 0))
    (should (equal (ne2wm:find-next-in-seq seq 0 -1) 4))
    (should (equal (ne2wm:find-next-in-seq seq 4 -1) 3))))
